Example: An implementation of the classic quicksort algorithm in Python

In [1]:
def quicksort(arr):
  if len(arr) <= 1:
    return arr
  
  pivot = arr[len(arr) // 2] # Floor division
  left = [x for x in arr if x < pivot]
  middle = [x for x in arr if x == pivot]
  right  = [x for x in arr if x > pivot]
  return quicksort(left) + middle + quicksort(right)

In [4]:
quicksort([7, 8, 1, 5, 9, 10, 2, 3, 6, 4])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

**Basic data types**

Numbers: Integers and floats work as you would expect from other languages

In [7]:
x = 5
print(type(x))

<class 'int'>


In [8]:
print(x)

5


In [9]:
print(x + 1) # Addition

6


In [10]:
print(x - 1)  # Subtraction

4


In [11]:
print(x * 2)  # Multiplication

10


In [12]:
print(x ** 2) # Exponentiation

25


In [13]:
x += 1

In [14]:
print(x)

6


In [15]:
x *= 2

In [16]:
print(x)

12


In [17]:
y = 1.5

In [18]:
print(type(y))

<class 'float'>


In [20]:
y, y + 1, y * 2, y ** 2

(1.5, 2.5, 3.0, 2.25)

Booleans: Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (&&, ||, etc)

In [24]:
t = True
f = False

In [25]:
print(type(t))

<class 'bool'>


In [26]:
print(t and f) # Logical AND

False


In [27]:
t or f  # Logical OR

True

In [28]:
print(not t) # Logical NOT

False


In [29]:
print(t != f) # Logical XOR

True


Strings: Python has great support for strings

In [30]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does no matter

In [33]:
print(hello)
print(len(hello))

hello
5


In [34]:
hw = hello + ' ' + world # String concatenation

In [35]:
hw

'hello world'

In [36]:
hw11 = '%s %s %d' % (hello, world, 11)  # sprintf style string formatting

In [37]:
hw11

'hello world 11'

**Containers**
Python includes serval buit-in container types: lists, dictionaries, sets, and tuples

List: A list the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [38]:
xl = [3, 1, 2]  # Crate a list

In [39]:
print(xl, xl[2])

[3, 1, 2] 2


In [42]:
print(xl[-3])

3


In [43]:
xl[2] = 'foo' # Lists can contain elements of different types

In [44]:
print(xl)

[3, 1, 'foo']


In [45]:
xl.append('bar')  # Add a new element to the end of the list

In [46]:
print(xl)

[3, 1, 'foo', 'bar']


In [47]:
x = xl.pop()

In [48]:
print(x)

bar


In [49]:
print(x, xl)

bar [3, 1, 'foo']


Slicing: In addition to accessing list elements one at a time, Python provides concise syntax to access sublists.

In [51]:
nums = list(range(5)) # range is a built-in function that crates a list of integers

In [52]:
print(nums)

[0, 1, 2, 3, 4]


In [56]:
print(nums[2:4])  # Get a slice from index 2 to 4 (exclusive)

[2, 3]


In [57]:
print(nums[2:]) # Get a slice from index 2 to the end

[2, 3, 4]


In [59]:
print(nums[:2]) # Get a slice from the start to index 2 (exclusive)

[0, 1]


In [60]:
print(nums[:])  # Get a slice of the whole list

[0, 1, 2, 3, 4]


In [63]:
print(nums[:-1])  # Slice indices can be negative

[0, 1, 2, 3]


In [64]:
nums[2:4] = [8, 9]  # Assign a new sublist to a slice

In [65]:
print(nums)

[0, 1, 8, 9, 4]


Loops: You can loop over the elements of a list like this:

In [68]:
animals = ['cat', 'dog', 'monky']
for animal in animals:
  print(animal)

cat
dog
monky


In [71]:
for idx, animal in enumerate(animals):  # access to the index of each element within the body of loop
  print('#%d:  %s' % (idx, animal))

#0:  cat
#1:  dog
#2:  monky


List comprehensions: When programming, frequently we want to transform one type of data into another.

In [73]:
nums = [0, 1, 2, 3, 4]
squares = []

for x in nums:
  squares.append(x ** 2) 

print(squares)

[0, 1, 4, 9, 16]


List conprehensions can also contain conditions:

In [74]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]

print(even_squares)

[0, 4, 16]


Dictionaries: A dictionary stores  (key, value) pairs, similar to a Map in Java or an object in Javascript.

In [75]:
d = {'cat': 'cute', 'dog': 'furry'} # Crate a new dictionary with some data

In [76]:
print(d['cat'])   # Get an entry from a ditionary

cute


In [89]:
print('cat1' in d) # Check if a dictionary has given key

False


In [90]:
d['fish'] = 'wet'   # Set an entry in a dictionary

In [91]:
print(d['fish'])

wet


In [92]:
print(d.get('monkey', 'N/A')) # Get an element with a default

N/A


In [93]:
print(d.get('fish', 'N/A')) # Get an element with a default

wet


In [94]:
del d['fish']   # Remove an element from a dictionary

In [95]:
print(d.get('fish', 'N/A')) # "fist" is no logner a key

N/A


Loops: It is easy to iterate over the keys in a dictionary

In [96]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
  legs = d[animal]
  
  print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [97]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
  print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Dictionary comprehensiions: These are similar to list comprehensions, but allow you to easily construct dictionaries

In [99]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}

print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


Sets: A set is an unordered collection of distinct elements

In [102]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set

True


In [103]:
print('fish' in animals)

False


In [104]:
animals.add('fish')

In [105]:
print('fish' in animals)

True


In [106]:
print(len(animals))

3


In [107]:
animals.add('cat')    # Adding an element that is already in the set does nothing

In [108]:
print(animals)

{'dog', 'cat', 'fish'}


In [109]:
animals.remove('cat')

In [110]:
print(len(animals))

2


**Fuctions**
Python functions are defined using the def keyword.


In [123]:
def sign(x):
  if x > 0:
    return 'positive'
  elif x < 0:
    return 'negative'
  else:
    return 'zero'

for x in [-1, 0, 1]:
  print(sign(x))

negative
zero
positive


In [126]:
def hello(name, loud=False):
  if loud:
    print("Hello, %s" % name.upper())
  else:
    print("Hello, %s" % name)

hello('John')

Hello, John


In [127]:
hello("Jane", loud=True)

Hello, JANE


**Numpy**
 is the core library for scientific computing in Python. It provides a high-performance multidimentional array object, and tools for working with these arrays.

**Arrays**
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

In [151]:
import numpy as np

a = np.array([1, 2, 3]) # Create a 1D array

In [152]:
print(type(a))

<class 'numpy.ndarray'>


In [153]:
print(a.shape)

(3,)


In [154]:
print(a[0], a[1], a[2])

1 2 3


In [155]:
a[0] = 5

In [156]:
print(a)

[5 2 3]


In [157]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [158]:
print(b.shape)

(2, 3)


In [159]:
print(b)

[[1 2 3]
 [4 5 6]]


**Array math**: Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module

In [160]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [161]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [162]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [163]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [164]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [165]:
print(np.sqrt(x))   # Elementwise square root

[[1.         1.41421356]
 [1.73205081 2.        ]]


**Python Library Installation**


In [169]:
!pip install scipy